### ISSUE TITLE
What if use other similarity metrics on the entity pair?

### ISSUE THREAD

**Issue by LiuYuLOL** [MaoXinn/RREA#1]
Hi, thanks for the great work. I got a lot of insights from the paper. Just wondering what if use other metrics, rather than ||e1-e2||, can we get a better result? or is the united framework still valid?

**Comment by MaoXinn** [comment]
Thanks for your attention.
According to my experiments, L1 distance is the optimal solution,&nbsp;L2 is slightly worse.
Under the current setting, cosine performs poorly.
The root cause needs to be further studied

--------------原始邮件--------------
发件人："LiuYuLOL "<notifications@github.com&gt;;
发送时间：2020年8月28日(星期五) 下午2:56
收件人："MaoXinn/RREA" <RREA@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[MaoXinn/RREA] What if use other similarity metrics on the entity pair? (#1)
-----------------------------------

 

 
Hi, thanks for the great work. I got a lot of insights from the paper. Just wondering what if use other metrics, rather than ||e1-e2||, can we get a better result? or is the united framework still valid?
